### ISSUE TITLE
送信メッセージの作成

### ISSUE THREAD

**Issue by URANOS-AIT** [AIT-Rescue/CommunicationLibrary#2]
一つに纏めて送るか、分割するか
・一回に付きのメッセージの量
・破損率

**Comment by tkmnet** [comment]
分割できます．
２ビットの修復でもコストが大きすぎるので，ハミング符号で１ビット修復か，パリティビットで破損データ検査で破棄かでいこうと思います．

---

・帯域オーバの場合は送信不可
・細切れ送信は帯域まで受信可
・データが黒塗りされた場合は帯域を妨害
・データが損失された場合は細切れ送信であふれた分を受信可
