### ISSUE TITLE
サーバの修正スクリプト

### ISSUE THREAD

**Issue by tkmnet** [AIT-Rescue/CommunicationLibrary#8]
以下をサーバのルートで実行してください．
ブートスクリプトのMacOS(**required xterm**), cshへの対応，コンフィグの修正，java8への対応が行われます．
**REQUIRED ENV: xterm wget**

```
wget https://gist.githubusercontent.com/tkmnet/d755253afe75adbe4896/raw/adc7f42433cc01cd26f3d4e3e7ed9a6011877bf4/fix-roborescue.sh
chmod a+x fix-roborescue.sh
./fix-roborescue.sh
```

**Comment by URANOS-AIT** [comment]
ありがとうございます

2014年11月5日 3:35 Shunki notifications@github.com:
